@extends('layouts.app')
@include('partials.metaTags')
@section('content')
    <div class="container-fluid terms-img d-flex align-items-center h-260 position-relative">
        <div class="container m-auto">
            <div class="col-12 text-white d-flex flex-column align-items-center justify-content-center">
                <div class="head1 py-2">
                    <div class="col-12">
                        <h5>Important Information Regarding Your Use</h5>
                    </div>
                </div>
                <div class="head2 py-2">
                    <div class="col-12">
                        <h1 class="fw-bold">Terms of Use</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('partials.livery-access-gif')
    <!-- terms of use -->
    <div class="container-fluid bg-lightGray py-5 px-sm-0 px-3">
        <div class="container m-auto pb-5">
            <div class="col-12 row d-flex justify-content-center">
                <div class="head text-center py-3">
                    <div class="col-12 pb-3">
                        <h1 class="fw-bold text-dark">Terms of use</h1>
                    </div>
                </div>
                <div class="col-lg-8 col-12">
                    <div class="policies">
                        <div class="policy py-2">
                            <div class="col-12">
                                <div class="head">
                                    <div class="col-12">
                                        <h3 class="text-darkParrot py-2 fw-bold" id="desc1">Liability Exclusion -</h3>
                                    </div>
                                </div>
                                <div class="desc">
                                    <div class="col-12">
                                        <p>IADAirport.com does the best to avoid any error in the contents appearing on this
                                            website.

                                            IADAirport.com does not guarantee the accuracy or information updated. Contents
                                            can be changed without notice.

                                            IADAirport.com assumes no liability for the use by others of the content of this
                                            website.

                                            All information contained is for information only. The information provided is
                                            not necessarily comprehensive, complete, accurate or current.

                                            The information provided by IADAirport.com is general and does not constitute
                                            professional or legal advice.

                                            IADAirport.com do the best effort to make the site not interrupted, but can not
                                            guarantee the absence of technological failure or the permanent availability of
                                            the site and the services it contains and therefore assumes no responsibility
                                            for damages that may be generated by the lack of availability and access
                                            failures caused by disconnection, breakdowns, overloads or network outages not
                                            attributable to IADAirport.com

                                            IADAirport.com does not guarantee the absence of viruses or other elements that
                                            may alter your computer system. IADAirport.com excludes all liability for
                                            damages of any kind arising from such viruses or harmful components.

                                            Links - As IADAirport.com has some external links may be some of the parts do
                                            not agree that any particular link, be part of IADAirport.com. In that case, we
                                            are aware of receiving the claim, through our contact us to remove the link in
                                            question, always if the demanding part show that the link belongs to it.

                                            Copyright - There is a possibility that some of the images and / or text
                                            appearing within the IADAirport.com come from several sources, including the
                                            network itself as the public domain, belonging therefore their rights
                                            (copyright) to their rightful owners. If the owner of any image and / or text
                                            wants to delete or ask for mention the font, please contact us via the CONTACT
                                            US, with the data to identify their legal ownership and the link within
                                            IADAirport.com, where you found that content.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
